name = "super-proxy-ahmedy22"
compatibility_date = "2025-04-13"
main = "worker.js"
worker_format = "service-worker"

compatibility_flags = ["nodejs_compat"]
workers_dev = true

[limits]
cpu_ms = 1000

[placement]
mode = "smart"
